### ISSUE TITLE
template to fsaverage5

### ISSUE THREAD

**Issue by tanjia123456** [faskowit/fsLR_2_fsaverage_4_labels#1]
Hello, I would like to ask you a question. After processing with freesurfer (recon all), there are too many vertices, there are more than 130,000. I see a paper that is registered to fsaverage5 (its vertices are only 10000+) to reduce The number of vertices, how is this registration operation realized?

**Comment by faskowit** [comment]
Hello, 

To get a surface from native subject space to fsaverage5 space, you can use [FreeSurfer's mri_surf2surf](http://freesurfer.net/fswiki/mri_surf2surf) command.  Here is an example of how to move an annot from fsaverage to fsaverage5: 

mri_surf2surf --srcsubject fsaverage --trgsubject fsaverage5  --hemi lh --sval-annot fsaverage_source_annot.annot --tval ./fsaverage5_target_annot.annot

But you can also use the function to go from a subject's surface to fsaverage5. I think (I'm not 100% sure) that to get to fsaverage5, you will first have to go to fsaverage, and then downsample that.  However, I am not totally sure.

**Comment by tanjia123456** [comment]
> 
> 
> Hello,
> 
> To get a surface from native subject space to fsaverage5 space, you can use [FreeSurfer's mri_surf2surf](http://freesurfer.net/fswiki/mri_surf2surf) command. Here is an example of how to move an annot from fsaverage to fsaverage5:
> 
> mri_surf2surf --srcsubject fsaverage --trgsubject fsaverage5 --hemi lh --sval-annot fsaverage_source_annot.annot --tval ./fsaverage5_target_annot.annot
> 
> But you can also use the function to go from a subject's surface to fsaverage5. I think (I'm not 100% sure) that to get to fsaverage5, you will first have to go to fsaverage, and then downsample that. However, I am not totally sure.

hi, if the file is rh.white ,how to template it to fsaverage?  I am not familiar with this mri_surf2surf command

**Comment by tanjia123456** [comment]
>  [FreeSurfer's mri_surf2surf](http://freesurfer.net/fswiki/mri_surf2surf)

by the way, this comand is shell?

**Comment by tanjia123456** [comment]
> mri_surf2surf --srcsubject fsaverage --trgsubject fsaverage5 --hemi lh --sval-annot fsaverage_source_annot.annot --tval ./fsaverage5_target_annot.annot

my freesurfer Related settings：
FREESURFER_HOME   /home/tj/application/freesurfer
FSFAST_HOME       /home/tj/application/freesurfer/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /home/tj/application/freesurfer/subjects
MNI_DIR           /home/tj/application/freesurfer/mni

rh.white located in: /home/tj/test

**Comment by faskowit** [comment]
Indeed, mri_surf2surf is a shell command. I think you will just have to read the help page for the command and try it out with different parameters, because I am not 100% sure about the command.

**Comment by tanjia123456** [comment]
> 
> 
> Indeed, mri_surf2surf is a shell command. I think you will just have to read the help page for the command and try it out with different parameters, because I am not 100% sure about the command.
ok ,thank you for your reply
